name: 'Setup Rust Environment'
description: 'Sets up Rust toolchain with sccache and caching'
inputs:
  toolchain:
    description: 'Rust toolchain to install'
    required: false
    default: 'stable'
  components:
    description: 'Additional components to install (comma-separated)'
    required: false
    default: ''
  cache-key:
    description: 'Custom cache key suffix'
    required: false
    default: 'default'
  save-cache:
    description: 'Whether to save cache (only for main branch)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
    
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.4
      shell: bash
    
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}-v2
        cache-on-failure: true
        save-if: ${{ inputs.save-cache }}
    
    - name: Show sccache version
      shell: bash
      run: sccache --version
