version: '3.8'

services:
  # Entry Mix Node (入口ノード)
  mix-node-1:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: nyx-mix-1
    networks:
      nyx-network:
        ipv4_address: 172.20.0.11
    environment:
      - NODE_ID=mix-node-1
      - NODE_ROLE=entry
      - NEXT_HOP=172.20.0.12:9001
      - LISTEN_PORT=9001
      - RUST_LOG=info
    ports:
      - "19001:9001"
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    command: >
      sh -c "
        echo 'Starting Mix Node 1 (Entry)...';
        python3 /workspace/scripts/mix-node-simulator.py
      "

  # Intermediate Mix Node 1 (中継ノード1)
  mix-node-2:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: nyx-mix-2
    networks:
      nyx-network:
        ipv4_address: 172.20.0.12
    environment:
      - NODE_ID=mix-node-2
      - NODE_ROLE=intermediate
      - NEXT_HOP=172.20.0.13:9001
      - LISTEN_PORT=9001
      - RUST_LOG=info
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    command: >
      sh -c "
        echo 'Starting Mix Node 2 (Intermediate 1)...';
        python3 /workspace/scripts/mix-node-simulator.py
      "

  # Intermediate Mix Node 2 (中継ノード2)
  mix-node-3:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: nyx-mix-3
    networks:
      nyx-network:
        ipv4_address: 172.20.0.13
    environment:
      - NODE_ID=mix-node-3
      - NODE_ROLE=intermediate
      - NEXT_HOP=172.20.0.14:9001
      - LISTEN_PORT=9001
      - RUST_LOG=info
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    command: >
      sh -c "
        echo 'Starting Mix Node 3 (Intermediate 2)...';
        python3 /workspace/scripts/mix-node-simulator.py
      "

  # Exit Mix Node (出口ノード)
  mix-node-4:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: nyx-mix-4
    networks:
      nyx-network:
        ipv4_address: 172.20.0.14
    environment:
      - NODE_ID=mix-node-4
      - NODE_ROLE=exit
      - LISTEN_PORT=9001
      - RUST_LOG=info
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    command: >
      sh -c "
        echo 'Starting Mix Node 4 (Exit)...';
        python3 /workspace/scripts/mix-node-simulator.py
      "

  # Benchmark Client
  benchmark-client:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: nyx-benchmark-client
    networks:
      nyx-network:
        ipv4_address: 172.20.0.10
    environment:
      - ENTRY_NODE=172.20.0.11:9001
      - RUST_LOG=info
    volumes:
      - ./benchmarks:/workspace/benchmarks
      - ./tests:/workspace/tests
      - ./target:/workspace/target
    depends_on:
      - mix-node-1
      - mix-node-2
      - mix-node-3
      - mix-node-4
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    command: >
      sh -c "
        echo 'Benchmark client ready';
        sleep infinity
      "

  # Network Delay Controller (遅延シミュレーション用)
  network-controller:
    image: alpine:latest
    container_name: nyx-network-controller
    networks:
      nyx-network:
        ipv4_address: 172.20.0.100
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - ./scripts:/scripts:ro
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /var/cache/apk:rw,noexec,nosuid,size=50m
    command: >
      sh -c "
        apk add --no-cache iproute2 bash python3;
        echo 'Network controller ready';
        sleep infinity
      "

networks:
  nyx-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
