kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nyx-cluster-1
networking:
  # cluster1のpodSubnet
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.96.0.0/16"
  # APIサーバーのポート (デフォルトから変更)
  apiServerPort: 6443
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "cluster=nyx-cluster-1"
    extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      protocol: TCP
    - containerPort: 30443
      hostPort: 30443
      protocol: TCP
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "cluster=nyx-cluster-1"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "cluster=nyx-cluster-1"
