---
# Namespace for NyxNet testing
apiVersion: v1
kind: Namespace
metadata:
  name: nyxnet-test

---
# ConfigMap for Mix Node configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nyx-config
  namespace: nyxnet-test
data:
  nyx.toml: |
    [network]
    listen_port = 9999
    max_connections = 100
    
    [crypto]
    algorithm = "ChaCha20Poly1305"
    
    [routing]
    num_hops = 3

---
# Mix Node 1
apiVersion: v1
kind: Pod
metadata:
  name: mix-node-1
  namespace: nyxnet-test
  labels:
    app: nyx-mix
    node: "1"
spec:
  containers:
  - name: nyx-daemon
    image: nyx-daemon:latest
    imagePullPolicy: Never  # Use local image
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false  # Daemon requires write access for state
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 9999
      protocol: UDP
    env:
    - name: NODE_ID
      value: "mix-1"
    - name: RUST_LOG
      value: "info"
    volumeMounts:
    - name: config
      mountPath: /etc/nyx
  volumes:
  - name: config
    configMap:
      name: nyx-config

---
# Mix Node 2
apiVersion: v1
kind: Pod
metadata:
  name: mix-node-2
  namespace: nyxnet-test
  labels:
    app: nyx-mix
    node: "2"
spec:
  containers:
  - name: nyx-daemon
    image: nyx-daemon:latest
    imagePullPolicy: Never
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false  # Daemon requires write access for state
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 9999
      protocol: UDP
    env:
    - name: NODE_ID
      value: "mix-2"
    - name: RUST_LOG
      value: "info"
    volumeMounts:
    - name: config
      mountPath: /etc/nyx
  volumes:
  - name: config
    configMap:
      name: nyx-config

---
# Mix Node 3
apiVersion: v1
kind: Pod
metadata:
  name: mix-node-3
  namespace: nyxnet-test
  labels:
    app: nyx-mix
    node: "3"
spec:
  containers:
  - name: nyx-daemon
    image: nyx-daemon:latest
    imagePullPolicy: Never
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false  # Daemon requires write access for state
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 9999
      protocol: UDP
    env:
    - name: NODE_ID
      value: "mix-3"
    - name: RUST_LOG
      value: "info"
    volumeMounts:
    - name: config
      mountPath: /etc/nyx
  volumes:
  - name: config
    configMap:
      name: nyx-config

---
# Services for each Mix Node
apiVersion: v1
kind: Service
metadata:
  name: mix-node-1
  namespace: nyxnet-test
spec:
  selector:
    node: "1"
  ports:
  - port: 9999
    targetPort: 9999
    protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: mix-node-2
  namespace: nyxnet-test
spec:
  selector:
    node: "2"
  ports:
  - port: 9999
    targetPort: 9999
    protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: mix-node-3
  namespace: nyxnet-test
spec:
  selector:
    node: "3"
  ports:
  - port: 9999
    targetPort: 9999
    protocol: UDP

---
# Benchmark Client Pod
apiVersion: v1
kind: Pod
metadata:
  name: benchmark-client
  namespace: nyxnet-test
  labels:
    app: nyx-benchmark
spec:
  containers:
  - name: benchmark
    image: nyx-daemon:latest
    imagePullPolicy: Never
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      seccompProfile:
        type: RuntimeDefault
    command: ["/bin/sleep", "infinity"]
    env:
    - name: MIX_NODE_1
      value: "mix-node-1.nyxnet-test.svc.cluster.local:9999"
    - name: MIX_NODE_2
      value: "mix-node-2.nyxnet-test.svc.cluster.local:9999"
    - name: MIX_NODE_3
      value: "mix-node-3.nyxnet-test.svc.cluster.local:9999"
