site_name: Nyx Documentation
site_description: Comprehensive specs, tutorials, and developer guides for the Nyx privacy-preserving mixnet.
repo_url: https://github.com/SeleniaProject/NyxNet
repo_name: SeleniaProject/NyxNet
copyright: "Copyright © Nyx Project contributors"
docs_dir: docs
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.instant
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SeleniaProject/NyxNet
nav:
  - Home: index.md
  - Quickstart (Ubuntu/k8s): quickstart-ubuntu-k8s.md
  - Architecture: architecture.md
  - Configuration: configuration.md
  - API: api.md
  - Specifications: specs.md
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.extra 
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
        zh: 中文 