# Nyx Network Configuration
# Basic network settings
listen_port = 43300
node_id = "auto"

# Logging
log_level = "info"

# Bootstrap peers for network discovery
bootstrap_peers = [
    "/dns4/validator1.nymtech.net/tcp/1789/p2p/12D3KooWNyxMainnet1",
    "/dns4/validator2.nymtech.net/tcp/1789/p2p/12D3KooWNyxMainnet2",
    "/dns4/testnet-validator1.nymtech.net/tcp/1789/p2p/12D3KooWNyxTestnet1"
]

# Network binding configuration
[network]
# Bind address - use 127.0.0.1 for security by default, change to specific IP for production
bind_addr = "127.0.0.1:43300"
# Development mode for localhost binding
development = true

# DHT configuration
[dht]
# Enable DHT peer discovery
enabled = true
# DHT bind port
port = 43301
# Peer cache size
peer_cache_size = 1000
# Discovery timeout in seconds
discovery_timeout = 30

# Service endpoints
[endpoints]
# gRPC control API address
grpc_addr = "127.0.0.1:50051"
# Prometheus metrics address  
prometheus_addr = "127.0.0.1:9090"

# CLI specific configuration
[cli]
# Maximum reconnect attempts for stream establishment / monitor logic
max_reconnect_attempts = 5

# Static safety limits
# Max codec frame length (bytes). Valid range: 1024..=67108864
max_frame_len_bytes = 8388608