{{- $hpa := (default (dict) .Values.hpa) -}}
{{- if $hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nyx.fullname" . }}
  minReplicas: {{ $hpa.minReplicas | default 1 }}
  maxReplicas: {{ $hpa.maxReplicas | default 3 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetCPUUtilizationPercentage | default 80 }}
{{- if $hpa.enableCustomPodsMetric }}
    - type: Pods
      pods:
        metric:
          name: nyx_bytes_sent_total
        target:
          type: AverageValue
          averageValue: {{ $hpa.targetBytesPerSecond | default "10k" }}
{{- end }}
{{- end }} 