{{- $ing := (default (dict) .Values.ingress) -}}
{{- if $ing.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
  annotations:
{{ toYaml ($ing.annotations | default (dict)) | indent 4 }}
spec:
  {{- if $ing.className }}
  ingressClassName: {{ $ing.className }}
  {{- end }}
  rules:
    {{- range ($ing.hosts | default (list)) }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "nyx.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- if $ing.tls }}
  tls:
{{ toYaml $ing.tls | indent 4 }}
  {{- end }}
{{- end }}


