{{- $np := (default (dict) .Values.networkPolicy) -}}
{{- if $np.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "nyx.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
  {{- range ($np.allowIngressFromNamespaces | default (list)) }}
      - namespaceSelector:
{{ toYaml .namespaceSelector | indent 10 }}
      {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
  egress:
    - to:
  {{- if $np.allowEgressDNS }}
      - namespaceSelector: {}
        ports:
          - protocol: UDP
            port: 53
          - protocol: TCP
            port: 53
      {{- end }}
{{- with $np.additionalIngressRules }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $np.additionalEgressRules }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}


