{{- $pdb := (default (dict) .Values.pdb) -}}
{{- if $pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
spec:
  minAvailable: {{ $pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
{{ include "nyx.selectorLabels" . | indent 6 }}
{{- end }} 