{{- if .Values.pushNotification.enabled -}}
---
# FCM credentials secret
{{- if .Values.pushNotification.fcm.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pushNotification.fcm.credentialsSecretName }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
    component: push-notification
type: Opaque
data:
  # Base64-encoded FCM service account JSON
  # Create with: kubectl create secret generic nyx-fcm-credentials --from-file=fcm-service-account.json
  # This is a placeholder - actual credentials must be provided externally
  fcm-service-account.json: ""
{{- end }}
---
# APNS credentials secret
{{- if .Values.pushNotification.apns.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pushNotification.apns.credentialsSecretName }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
    component: push-notification
type: Opaque
data:
  # Base64-encoded APNS certificate and key
  # Create with: kubectl create secret generic nyx-apns-credentials \
  #   --from-file=apns-cert.pem --from-file=apns-key.pem
  # This is a placeholder - actual credentials must be provided externally
  apns-cert.pem: ""
  apns-key.pem: ""
{{- end }}
{{- end }}
