apiVersion: v1
kind: Service
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "nyx.selectorLabels" . | indent 4 }}
  ports:
    - name: transport
      port: {{ .Values.service.port }}
      targetPort: 43300
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
{{- if and (.Values.service.loadBalancerSourceRanges) (eq .Values.service.type "LoadBalancer") }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}