{{- $st := index .Values "stateful" -}}
{{- if and $st (index $st "enabled") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
spec:
  serviceName: {{ include "nyx.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "nyx.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "nyx.selectorLabels" . | indent 8 }}
    spec:
      securityContext:
{{- $ps := (default (dict) .Values.podSecurity) -}}
{{- $sp := (default (dict) $ps.seccompProfile) -}}
{{- if $sp.type }}
        seccompProfile:
          type: {{ $sp.type }}
{{- if eq $sp.type "Localhost" }}
          localhostProfile: {{ $sp.localhostProfile | quote }}
{{- end }}
{{- else }}
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      containers:
        - name: nyxd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
{{ toYaml (.Values.securityContext | default (dict)) | indent 12 }}
          ports:
            - containerPort: 43300
            - containerPort: {{ .Values.service.metricsPort }}
          volumeMounts:
            - name: config
              mountPath: {{ (default (dict) .Values.config).mountPath | default "/etc/nyx" }}
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: false
          env:
            - name: NYX_CONFIG
              value: "{{ (default (dict) .Values.config).mountPath | default "/etc/nyx" }}/{{ (default (dict) .Values.config).fileName | default "nyx.toml" }}"
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "nyx.fullname" . }}
            items:
              - key: {{ (default (dict) .Values.config).fileName | default "nyx.toml" }}
                path: {{ (default (dict) .Values.config).fileName | default "nyx.toml" }}
        - name: tmp
          emptyDir: {}
{{- end }}