# Default values for nyx.
replicaCount: 2

image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: "3.19"

service:
  type: ClusterIP
  port: 43300
  metricsPort: 9090

bench:
  enabled: false
  image: alpine:3.19
  replicas: 1
  testDurationSeconds: 30
  concurrentConnections: 5

serviceMonitor:
  enabled: false

pdb:
  enabled: false

probes:
  startup:
    enabled: false
  liveness:
    enabled: false
  readiness:
    enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
    enabled: false  
  readiness:
    enabled: false