# Default values for nyx.
replicaCount: 6

# Multi-node settings
multinode:
  enabled: true
  antiAffinity: true
  distributePods: true

image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: "3.19"

# Daemon configuration
daemon:
  command: ["/bin/sh"]
  args:
    - "-c"
    - |
      # Install netcat if not available
      if ! command -v nc >/dev/null 2>&1; then
        echo "Installing netcat-openbsd..."
        apk add --no-cache netcat-openbsd
      fi
      
      echo "Starting mock daemon on port 43300..."
      while true; do
        echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 2\r\n\r\nOK" | nc -l -p 43300
        sleep 0.1
      done

service:
  type: ClusterIP
  port: 43300
  metricsPort: 9090

bench:
  enabled: false
  image: alpine:3.19
  replicas: 1
  testDurationSeconds: 30
  concurrentConnections: 5

serviceMonitor:
  enabled: false

pdb:
  enabled: false

probes:
  startup:
    enabled: false
  liveness:
    enabled: false
  readiness:
    enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi