# Values for kind local testing with full production features
image:
  repository: nyx-daemon
  tag: local
  pullPolicy: IfNotPresent

podSecurity:
  seccompProfile:
    type: RuntimeDefault

replicaCount: 3

# Disable probes for faster startup in kind
probes:
  startup:
    enabled: false
  liveness:
    enabled: false
  readiness:
    enabled: false

# Enable comprehensive benchmarking
bench:
  enabled: true

# Enable production features for testing
pdb:
  enabled: true
  minAvailable: 2

serviceMonitor:
  enabled: true

# Optimized resources for kind
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
